dotVersionFiles:
  - example-project/Directive.yaml
  - atmo/release/version.go

preMakeTargets:
  - build
  - test

postMakeTargets:
  - docker/publish version={{ .Version }}
  - docker/publish/latest